[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'


# lsp + gopl
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'mattn/vim-lsp-settings'
[[plugins]]
repo = 'mattn/vim-goimports'
# end

[[plugins]]
repo = 'mattn/vim-lexiv'

[[plugins]]
repo = 'leafgarland/typescript-vim'
