[[plugins]]
repo = 'ghifarit53/tokyonight-vim'
hook_add = '''
set termguicolors

let g:tokyonight_style = 'night' " available: night, storm
let g:tokyonight_enable_italic = 1
let g:lightline = {'colorscheme' : 'tokyonight'}
let g:airline_theme = "tokyonight"

colorscheme tokyonight
'''
