[[plugins]]
repo = 'scrooloose/nerdtree'

# lsp + gopl
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'mattn/vim-lsp-settings'
[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'mattn/vim-lsp-icons'
# end

[[plugins]]
repo = 'mattn/vim-lexiv'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'mattn/vim-maketable'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
