[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']
hook_add = '''
    let g:jedi#popup_on_dot = 0
    let g:jedi#popup_select_first = 0
    autocmd FileType python setlocal completeopt-=preview
'''

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = ['python']
hook_add = '''
    let g:autopep8_on_save = 1
'''

[[plugins]]
repo = 'tell-k/vim-autopep8'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

