[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = ['python']
hook_add = '''
    let g:autopep8_on_save = 1
    let g:autopep8_disable_show_diff=1
'''

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build ='''
cd app & yarn install
'''

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'heavenshell/vim-jsdoc'
on_ft = ['typescript']
